//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 04:05:37 PM CET 
//


package com.esiag.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageFormater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageFormater">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codeTypeEvenement" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="position" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Criticite" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageFormater")
@XmlRootElement
public class MessageFormater {

    @XmlAttribute(name = "Source", required = true)
    protected String source;
    @XmlAttribute(name = "codeTypeEvenement", required = true)
    protected int codeTypeEvenement;
    @XmlAttribute(name = "position", required = true)
    protected String position;
    @XmlAttribute(name = "Criticite", required = true)
    protected int criticite;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the codeTypeEvenement property.
     * 
     */
    public int getCodeTypeEvenement() {
        return codeTypeEvenement;
    }

    /**
     * Sets the value of the codeTypeEvenement property.
     * 
     */
    public void setCodeTypeEvenement(int value) {
        this.codeTypeEvenement = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the criticite property.
     * 
     */
    public int getCriticite() {
        return criticite;
    }

    /**
     * Sets the value of the criticite property.
     * 
     */
    public void setCriticite(int value) {
        this.criticite = value;
    }

}
