
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "InformationsServicesImplService", targetNamespace = "http://services.pds.com/", wsdlLocation = "http://localhost:8888/InformationsServices?wsdl")
public class InformationsServicesImplService
    extends Service
{

    private final static URL INFORMATIONSSERVICESIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/InformationsServices?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        INFORMATIONSSERVICESIMPLSERVICE_WSDL_LOCATION = url;
    }

    public InformationsServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InformationsServicesImplService() {
        super(INFORMATIONSSERVICESIMPLSERVICE_WSDL_LOCATION, new QName("http://services.pds.com/", "InformationsServicesImplService"));
    }

    /**
     * 
     * @return
     *     returns InformationsServices
     */
    @WebEndpoint(name = "InformationsServicesImplPort")
    public InformationsServices getInformationsServicesImplPort() {
        return (InformationsServices)super.getPort(new QName("http://services.pds.com/", "InformationsServicesImplPort"), InformationsServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InformationsServices
     */
    @WebEndpoint(name = "InformationsServicesImplPort")
    public InformationsServices getInformationsServicesImplPort(WebServiceFeature... features) {
        return (InformationsServices)super.getPort(new QName("http://services.pds.com/", "InformationsServicesImplPort"), InformationsServices.class, features);
    }

}
